- name: Configurar servidor Apache
  hosts: all
  become: yes
  tasks:
  - name: Instalar Apache
    apt:
      name: apache2
      state: present

  - name: Crear página index.html
    copy:
      content: "<h1>Hola Mundo</h1>"
      dest: /var/www/html/index.html

  - name: Habilitar Apache
    service:
      name: apache2
      state: started
      enabled: yes
